environment            = "dev"
contact                = "Equipe DCube Learning"
resource_group_name    = "rg-learning-template-dev"
app_configuration_name = "acf-learning-template-dev"
app_configuration_sku  = "free"
service_bus_name       = "sbu-learning-template-dev"
service_bus_sku_name   = "basic"